# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProbablyNoTea.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 637)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_chosenOption = QtWidgets.QLabel(self.centralwidget)
        self.lbl_chosenOption.setGeometry(QtCore.QRect(120, 130, 251, 16))
        self.lbl_chosenOption.setStyleSheet("")
        self.lbl_chosenOption.setObjectName("lbl_chosenOption")
        self.lbl_param_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_param_1.setGeometry(QtCore.QRect(100, 250, 91, 16))
        self.lbl_param_1.setStyleSheet("")
        self.lbl_param_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_param_1.setObjectName("lbl_param_1")
        self.lbl_param_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_param_2.setGeometry(QtCore.QRect(200, 250, 91, 16))
        self.lbl_param_2.setStyleSheet("")
        self.lbl_param_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_param_2.setObjectName("lbl_param_2")
        self.lbl_param_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_param_3.setGeometry(QtCore.QRect(300, 250, 91, 16))
        self.lbl_param_3.setStyleSheet("")
        self.lbl_param_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_param_3.setObjectName("lbl_param_3")
        self.combo_asked_param = QtWidgets.QComboBox(self.centralwidget)
        self.combo_asked_param.setGeometry(QtCore.QRect(180, 160, 111, 22))
        self.combo_asked_param.setStyleSheet("")
        self.combo_asked_param.setObjectName("combo_asked_param")
        self.combo_asked_param.addItem("")
        self.combo_asked_param.addItem("")
        self.combo_asked_param.addItem("")
        self.combo_asked_param.addItem("")
        self.combo_asked_param.addItem("")
        self.line_param_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.line_param_1.setGeometry(QtCore.QRect(100, 270, 91, 31))
        self.line_param_1.setStyleSheet("")
        self.line_param_1.setObjectName("line_param_1")
        self.line_param_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.line_param_2.setGeometry(QtCore.QRect(200, 270, 91, 31))
        self.line_param_2.setStyleSheet("")
        self.line_param_2.setObjectName("line_param_2")
        self.line_param_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.line_param_3.setGeometry(QtCore.QRect(300, 270, 91, 31))
        self.line_param_3.setStyleSheet("")
        self.line_param_3.setObjectName("line_param_3")
        self.btn_calc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc.setGeometry(QtCore.QRect(190, 320, 111, 51))
        self.btn_calc.setStyleSheet("    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"background-color: rgb(93, 233, 0);")
        self.btn_calc.setObjectName("btn_calc")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(130, 390, 231, 16))
        self.lbl_result.setStyleSheet("")
        self.lbl_result.setText("")
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_chosenOption.setText(_translate("MainWindow", "Please input the parameters in question"))
        self.lbl_param_1.setText(_translate("MainWindow", "-"))
        self.lbl_param_2.setText(_translate("MainWindow", "-"))
        self.lbl_param_3.setText(_translate("MainWindow", "-"))
        self.combo_asked_param.setCurrentText(_translate("MainWindow", "-"))
        self.combo_asked_param.setItemText(0, _translate("MainWindow", "-"))
        self.combo_asked_param.setItemText(1, _translate("MainWindow", "P(A)"))
        self.combo_asked_param.setItemText(2, _translate("MainWindow", "P(B)"))
        self.combo_asked_param.setItemText(3, _translate("MainWindow", "P(A|B)"))
        self.combo_asked_param.setItemText(4, _translate("MainWindow", "P(B|A)"))
        self.btn_calc.setText(_translate("MainWindow", "CALCULATE"))
